### ISSUE TITLE
Configuring signing profile

### ISSUE THREAD

**Issue by EugeneFinch** [aws-samples/eth-keygen-lambda-sam#5]
Hi, 

I've got an issue when setting up signing profile. I mistakenly revoked profile "Test1" and can't seem to use this name anymore.

aws signer put-signing-profile --platform-id "AWSLambda-SHA384-ECDSA" --profile-name Test1

When trying to create new profile with arbitrary name "e.g. Test3" , it throws errors during SAM deployment process, assuming profile should still be called "Test1". 

Where can I edit this to enable alternative names? 

Thanks,

**Comment by frbrkoala** [comment]
Hi Eugine.

I double-checked the code and the name of the profile is not hard coded there. After profile creation with this step: https://github.com/aws-samples/eth-keygen-lambda-sam#create-signing-profile , the signing profile's ARN (Amazon Resource Name) is passed over to `sam deploy` command through `SIGNING_PROFILE_ARN` variable. To set that variable we use command `aws signer get-signing-profile --profile-name Test1 --query profileVersionArn --output text`, where we still use `Test1` as profile name. Let's make sure that you change the name of the profile in that command to `Test3`, like this:

`SIGNING_PROFILE_ARN=$(aws signer get-signing-profile --profile-name Test3 --query profileVersionArn --output text)`

And run the same `sam deploy` command again:

```bash
sam deploy \
 --region $AWS_DEFAULT_REGION \
 --stack-name secure-keygen \
 --template-file ./.aws-sam/build/template.yaml \
 --parameter-overrides SigningProfileVersionArnParameter=$SIGNING_PROFILE_ARN \
 --signing-profiles ValidatorKeyGenFunction=Test1 \
 --confirm-changeset \
 --capabilities CAPABILITY_IAM \
 --no-disable-rollback
```
 
 See this step for more details: https://github.com/aws-samples/eth-keygen-lambda-sam#deploy
 
 If that will not work, please copy/paste commands you enter into your console and the error message. That will tremendously help with debugging :)
